name: Ecommerce App Deployment

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

jobs:
    build_and_push:
        runs-on: ubuntu-latest
        steps:
            - name: Copying Code to the machine
              uses: actions/checkout@v4
            
            - name: Login to Docker
              uses: docker/login-action@v3
              with:
                username: ${{vars.DOCKER_USERNAME}}
                password: ${{secrets.DOCKERHUB_TOKEN}}
            
            - name: Build Frontend Project
              run: |
                docker build -t ${{vars.DOCKER_USERNAME}}/backend:latest ./server
                docker push ${{vars.DOCKER_USERNAME}}/backend:latest
            
            
            - name: Build Frontend Project
              run: |
                docker build -t ${{vars.DOCKER_USERNAME}}/frontend:latest ./client
                docker push ${{vars.DOCKER_USERNAME}}/frontend:latest
            
             
              

