name: Ecommerce App Deployment

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

jobs:
    build_and_push:
        runs-on: ubuntu-latest
        steps:
            - name: Copying Code to the machine
              uses: actions/checkout@v4
            
            - name: Login to Docker
              uses: docker/login-action@v3
              with:
                username: ${{vars.DOCKER_USERNAME}}
                password: ${{secrets.DOCKERHUB_TOKEN}}
            
            - name: Build Frontend Project
              run: |
                docker build -t ${{vars.DOCKER_USERNAME}}/backend:latest ./server
                docker push ${{vars.DOCKER_USERNAME}}/backend:latest
            
            
            - name: Build Frontend Project
              run: |
                docker build -t ${{vars.DOCKER_USERNAME}}/frontend:latest ./client
                docker push ${{vars.DOCKER_USERNAME}}/frontend:latest
    deploy:
        runs-on: ubuntu-latest
        needs:  build_and_push
        steps: 
            - name: Login to Server
              uses: appleboy/ssh-action@master
              with:
                host: ${{secrets.EC2_HOST_SERVER}}
                username: ${{secrets.EC2_USERNAME}}
                key: ${{secrets.EC2_PRIVATE_KEY}}
                script: |
                    cd /home/ubuntu/david
                    sudo docker login -u ${{vars.DOCKER_USERNAME}} -p ${{secrets.DOCKERHUB_TOKEN}}
                    sudo docker-compose pull
                    sudo docker-compose down
                    sudo docker-compose up -d

              

